name: design
description: "A new Flutter project with internet connectivity detection."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  battery: ^2.0.3
  connectivity: ^3.0.6
  flutter_local_notifications: ^17.2.1
  cloud_firestore: ^4.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.3
  flutter_facebook_auth: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true